<a href="https://colab.research.google.com/github/VANSHKALRA88/NLP-Based-Text-Classification-System-/blob/main/NLP_OWN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import os
os.listdir()

['.config', 'sample_data']

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.txt.zip to train.txt.zip

In [ ]:
df = pd.read_csv('train.txt.zip', sep=';', header=None, names=['text','emotion'])

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
unique_emotion=df['emotion'].unique()
emotion_number={}
i=0
for emo in unique_emotion:
    emotion_number[emo]=i
    i+=1

df['emotion']=df['emotion'].map(emotion_number)

In [ ]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
df['text']=df['text'].apply(lambda x: x.lower())

In [ ]:
import string
def remove_punctuation(x):
    return x.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['text']=df['text'].apply(remove_punctuation)

In [ ]:
def remove_numbers(txt):
  new=''
  for i in txt:
    if not i.isdigit():
      new+=i
  return new
df['text']=df['text'].apply(remove_numbers)

In [ ]:
def remove_emojis(txt):
  new=''
  for i in txt:
    if i.isascii():
      new+=i
  return new

df['text']=df['text'].apply(remove_emojis)

In [ ]:
import nltk

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words=set(stopwords.words('english'))

In [ ]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
def remove(txt):
  words=word_tokenize(txt)
  cleaned_text=[]
  for i in words:
    if not i in stop_words:
      cleaned_text.append(i)
  return ' '.join(cleaned_text)

In [ ]:
df['text']=df['text'].apply(remove)

In [ ]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

 HOT ENCODING PROS= IT IS INTUTIVE (EASY TO UNDERSTAND) , IT IS EASY TO IMPLEMENT

CONS = SPARSITY- TOO MANY ZEROS , OOV(OUT OF VOCABULARY) , SIZE DIFFERENCE ,
SEMANTIC MEANING IS NOT GETTING CAPTURED

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
...     df['text'], df['emotion'], test_size=0.20, random_state=42)

In [ ]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [ ]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [ ]:
bow_vectorizer=CountVectorizer()

In [ ]:
x_train_bow=bow_vectorizer.fit_transform(X_train)
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [ ]:
x_test_bow=bow_vectorizer.transform(X_test)
x_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26934 stored elements and shape (3200, 13359)>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

FOR CLASSIFICATION OR FREQUENCY AND STOPWORDS THEN WE USE MULTINOMIAL NAIVE BIAS

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
nb_model=MultinomialNB()
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [ ]:
pred_nb=nb_model.predict(x_test_bow)

In [ ]:
print(accuracy_score(y_test,pred_nb))

0.7678125

In [ ]:
tfidf_vectorizer=TfidfVectorizer()

In [ ]:
x_train_tfidf=tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf=tfidf_vectorizer.transform(X_test)

In [ ]:
nb2_model=MultinomialNB()

In [ ]:
nb2_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [ ]:
y_pred=nb2_model.predict(x_test_tfidf)

In [ ]:
print(accuracy_score(y_test,y_pred))

0.6609375

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logistic_model=LogisticRegression(max_iter=1000)

In [ ]:
logistic_model.fit(x_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
log_pred=logistic_model.predict(x_test_tfidf)

In [ ]:
print(accuracy_score(y_test,log_pred))

0.8615625